[workspace]
resolver = "2"

members = [
    "xor64_bindef"
]


[workspace.package]
name = "xor64_ftb"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
